name: PHPUnit

on:
  push:
    branches:
      - main   # Run the tests on push to the main branch
  pull_request:
    branches:
      - '*'   # Run the tests on pull requests to the main branch

jobs:
  phpunit:

    name: Run PHPUnit tests

    runs-on: ubuntu-latest

    
        

    steps:
    - name: Checkout code
    
      uses: actions/checkout@v3

    - name: Set up PHP

      uses: shivammathur/setup-php@v2

      with:
        php-version: '8.3.6'

        extensions: mbstring, pdo, pdo_mysql, curl  # Add any required PHP extensions

        coverage: none

    - name: Install Composer dependencies
      run: composer install -n --prefer-dist

    - name: Run PHPUnit tests
      run: k:\data\CodeIgniter-4.4.5-Shared\vendor\bin\phpunit 
      
#--configuration phpunit.xml  # Adjust the path to your phpunit.xml if needed
#PHPUNIT_PATH=k:\data\CodeIgniter-4.4.5-Shared\vendor\bin\phpunit --no-coverage